# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAddUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdUserfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls_file', models.FileField(upload_to='upload/xls/%Y/%m/')),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupReleation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adtree', models.CharField(max_length=100, verbose_name='ad\u76ee\u5f55\u6811')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='\u90e8\u95e8')),
                ('attachto', models.CharField(max_length=200, verbose_name='\u96b6\u5c5e\u4e8e')),
                ('company', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='adadduserlog',
            name='aduserfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admanage.AdUserfile'),
        ),
    ]
