# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('tel', models.CharField(max_length=50, verbose_name='\u5ba2\u670d\u7535\u8bdd')),
                ('address', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='ip\u5730\u5740')),
                ('netmask', models.CharField(max_length=21, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('type', models.CharField(choices=[(b'in', '\u5185\u7f51'), (b'out', '\u5916\u7f51'), (b'pub', '\u516c\u7f51'), (b'manager', '\u7ba1\u7406\u5730\u5740')], max_length=50, verbose_name='\u7c7b\u578b')),
                ('status', models.BooleanField(default=True, help_text='\u662f\u5426\u5728\u7528', verbose_name='\u72b6\u6001')),
                ('idc', models.ForeignKey(blank=True, help_text='\u5c5e\u4e8e\u54ea\u4e2aIDC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='idc.Idc', verbose_name='IDC')),
            ],
        ),
        migrations.CreateModel(
            name='iptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idc.Idc')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
