# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0013_auto_20161108_1507'),
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=b'upload/image', verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x9b\xbe')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcenter.datacenter', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83')),
            ],
        ),
    ]
