# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0002_racks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racks',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idc.Idc', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83'),
        ),
    ]
