# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-10 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0003_auto_20161108_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racks',
            name='pic',
            field=models.ImageField(upload_to=b'static/upload/img', verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x9b\xbe'),
        ),
    ]
