# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-14 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0004_auto_20161108_1658'),
        ('idc', '0004_auto_20161110_1452'),
    ]

    operations = [
    ]
