# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-04 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='status',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='inuse',
            field=models.BooleanField(default=False, help_text='\u662f\u5426\u5728\u7528', verbose_name='\u72b6\u6001'),
        ),
    ]
