# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcenter', '0014_auto_20170204_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorHostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.IntegerField(verbose_name='\u76d1\u63a7id')),
                ('status', models.BooleanField(default=False)),
                ('check_datatime', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcenter.virtualhost')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('url', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('user', models.CharField(max_length=100, verbose_name='\u7528\u6237')),
                ('password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
            ],
        ),
        migrations.AddField(
            model_name='monitorhostdetail',
            name='monitor_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.MonitorServer'),
        ),
    ]
