# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u9891\u9053\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='LiveNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('protocol', models.CharField(choices=[('rtmp', 'rtmp'), ('http', 'http')], max_length=10, verbose_name='\u534f\u8bae')),
                ('address', models.GenericIPAddressField(verbose_name='\u5730\u5740')),
                ('channal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.LiveChannel', verbose_name='\u9891\u9053')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('stream_type', models.CharField(choices=[('rtmp', 'rtmp'), ('hls', 'hls')], max_length=10, verbose_name='\u7c7b\u578b')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
        ),
    ]
