#-*- coding: utf-8 -*-
#Generated by Django 1.9.4 on 2016-11-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='\u57df\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u8bb0\u5f55')),
                ('type', models.CharField(choices=[('A', 'A'), ('CHAME', 'CHAME'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA')], default='A', max_length=20, verbose_name='\u8bb0\u5f55\u7c7b\u578b')),
                ('data', models.TextField(blank=True, max_length=255, verbose_name='\u8bb0\u5f55\u503c')),
                ('ttl', models.IntegerField(default=600)),
                ('mx_priority', models.IntegerField(null=True, verbose_name='MX\u4f18\u5148\u7ea7')),
                ('refresh', models.IntegerField(default=3600)),
                ('retry', models.IntegerField(default=3600)),
                ('expire', models.IntegerField(default=600)),
                ('minimum', models.IntegerField(default=3600)),
                ('serial', models.BigIntegerField(default=20161107)),
                ('resp_person', models.CharField(blank=True, max_length=255)),
                ('primary_ns', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', '\u5728\u7ebf'), ('offline', '\u79bb\u7ebf')], default='online', max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bind.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='xfr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
            ],
        ),
    ]
