# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtualhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('cpu', models.CharField(max_length=50, null=True)),
                ('memory', models.CharField(max_length=50, null=True)),
                ('disk', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('system', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('tag', models.CharField(max_length=255, null=True, verbose_name='\u6807\u7b7e')),
                ('esxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcenter.host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vm',
            name='esxi',
        ),
        migrations.DeleteModel(
            name='vm',
        ),
    ]
