# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0003_auto_20160930_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualhost',
            name='system',
            field=models.CharField(max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
    ]
