# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0005_auto_20160930_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
