# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0006_auto_20161008_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(max_length=255),
        ),
    ]
