# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0007_auto_20161008_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualhost',
            name='vmuuid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualhost',
            name='cpu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
