# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0008_auto_20161010_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualhost',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, default='2016-10-10 00:00:00'),
            preserve_default=False,
        ),
    ]
