# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0011_auto_20161010_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='upload/image', verbose_name='\u673a\u67dc\u56fe')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcenter.datacenter', verbose_name='\u6570\u636e\u4e2d\u5fc3')),
            ],
        ),
    ]
