# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0012_racks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racks',
            name='idc',
        ),
        migrations.DeleteModel(
            name='Racks',
        ),
    ]
