# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-04 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0013_auto_20161108_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='servercontainer',
            new_name='esxi_groups',
        ),
    ]
