# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160624_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
