# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacRegLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checktime', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=200)),
            ],
        ),
    ]
