# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macreglog',
            options={'ordering': ['-checktime']},
        ),
        migrations.AddField(
            model_name='macreglog',
            name='authuser',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macreglog',
            name='switch',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
