# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcenter', '0011_auto_20161010_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0002_auto_20161014_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatePremissionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcenter.virtualhost')),
                ('opuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op', to=settings.AUTH_USER_MODEL)),
                ('vsauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
