# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-13 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_hostloginevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsxiScanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True)),
                ('scanresult', models.IntegerField()),
            ],
        ),
    ]
