# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-13 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('md5', models.CharField(max_length=50)),
                ('md5_auto', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/commonfile/%Y/%m/%d/%H/%M/%S/')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-upload_time',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('inuse', models.BooleanField(default=False, help_text='\u662f\u5426\u5728\u7528', verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('md5', models.CharField(max_length=50)),
                ('md5_auto', models.CharField(max_length=50)),
                ('file', models.FileField(max_length=2048, upload_to='upload/mypackage/%Y/%m/%d/%H/%M/%S/')),
                ('create_release_list', models.BooleanField(default=0)),
            ],
            options={
                'ordering': ('-upload_time',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('deploy_path', models.CharField(blank=True, max_length=255)),
                ('backup_path', models.CharField(blank=True, max_length=255)),
                ('service_stop_command', models.CharField(blank=True, max_length=255)),
                ('service_start_command', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('md5', models.CharField(max_length=50)),
                ('md5_auto', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/script/%Y/%m/%d/%H/%M/%S/')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Project')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Project'),
        ),
        migrations.AddField(
            model_name='package',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
