# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanage', '0003_auto_20161103_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adadduserlog',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='adadduserlog',
            name='adaccount',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u90ae\u4ef6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='adadduserlog',
            name='aduser',
            field=models.CharField(blank=True, max_length=50, verbose_name='ad\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='adadduserlog',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='adadduserlog',
            name='vlangroup',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
