# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanage', '0005_auto_20161104_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduserfile',
            name='xls_file',
            field=models.FileField(upload_to='upload/xls/%Y/%m/%d/%H/%M'),
        ),
    ]
