# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-22 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifylog',
            name='notifyuser',
        ),
        migrations.AddField(
            model_name='notifylog',
            name='detail',
            field=models.TextField(default=1, verbose_name='\u901a\u77e5\u8be6\u60c5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifylog',
            name='notifyusers',
            field=models.TextField(default=1, verbose_name='\u88ab\u901a\u77e5\u7528\u6237'),
            preserve_default=False,
        ),
    ]
